# -*- coding: utf-8 -*-
"""Ass 7 NumPy and Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lmgk_z7JCl_sU0AWs1g2o1qmWocLcJQ0
"""

# Exercise 1: NumPy array from 1 to 10 and reshape to 2x5

import numpy as np
import pandas as pd

arr1 = np.arange(1, 11)
reshaped_arr = arr1.reshape(2, 5)
print("Exercise 1: Reshaped Array (2x5):")
print(reshaped_arr)
print()

# Exercise 2: NumPy array from 1 to 20 and extract elements between 5th and 15th index

arr2 = np.arange(1, 21)
extracted = arr2[5:16]  # includes 15th index (Python indexing)
print("Exercise 2: Elements from 5th to 15th index:")
print(extracted)
print()

# Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1} and add 'pears'

fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
fruit_series['pears'] = 4
print("Exercise 3: Fruit Series with Pears added:")
print(fruit_series)
print()

#  Exercise 4: Create a DataFrame with 10 rows( with the following columns: name, age, and gender. The dataframe should have 10 rows of data)

data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah', 'Ian', 'Julia'],
    'age': [25, 30, 22, 35, 29, 40, 28, 32, 26, 31],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'F']
}
df = pd.DataFrame(data)
print("Exercise 4: DataFrame with 10 rows:")
print(df)
print()

#  Exercise 5: Add a new column 'occupation'

occupations = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager',
               'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
df['occupation'] = occupations
print("Exercise 5: DataFrame with 'occupation' column added:")
print(df)
print()

#  Exercise 6: Select rows where age >= 30

age_filtered = df[df['age'] >= 30]
print("Exercise 6: Rows with age >= 30:")
print(age_filtered)
print()

# ✅ Exercise 7: Convert to CSV, read it back, and display

csv_filename = "people_data.csv"
df.to_csv(csv_filename, index=False)

# Read back the CSV

df_from_csv = pd.read_csv(csv_filename)
print("Exercise 7: Data read from CSV file:")
print(df_from_csv)

